export let darkColors = [
  {
    id: 'theme-color-1',
    basedOn: 'light',
    backgroundHeader: 'rgb(41, 27, 24)',
    colorText: 'light',
    themeBg: 'rgb(74, 53, 47)',
  },
  {
    id: 'theme-color-2',
    basedOn: 'light',
    backgroundHeader: 'rgb(36, 36, 36)',
    colorText: 'light',
    themeBg: 'rgb(66, 66, 66)',
  },
  {
    id: 'theme-color-3',
    basedOn: 'light',
    backgroundHeader: 'rgb(51, 29, 51)',
    colorText: 'light',
    themeBg: 'rgb(90, 53, 90)',
  },
  {
    id: 'theme-color-4',
    basedOn: 'light',
    backgroundHeader: 'rgb(23, 25, 40)',

    colorText: 'light',
    themeBg: 'rgb(53, 56, 90)',
  },
  {
    id: 'theme-color-5',
    basedOn: 'light',
    backgroundHeader: 'rgb(67, 76, 152)',
    colorText: 'light',
    themeBg: 'rgb(100, 110, 203)',
  },
  {
    id: 'theme-color-6',
    basedOn: 'light',
    backgroundHeader: 'rgb(179, 28, 79)',
    colorText: 'light',
    themeBg: 'rgb(231, 54, 114)',
  },
  {
    id: 'theme-color-7',
    basedOn: 'light',
    backgroundHeader: 'rgb(183, 48, 38)',
    colorText: 'light',
    themeBg: 'rgb(244, 67, 54)',
  },
  {
    id: 'theme-color-8',
    basedOn: 'light',
    backgroundHeader: 'rgb(39, 102, 42)',
    colorText: 'light',
    themeBg: 'rgb(56, 142, 60)',
  },
]
export let lightColors = [
  {
    id: 'theme-color-9',
    basedOn: 'light',
    backgroundHeader: 'rgb(60, 146, 138)',
    colorText: 'dark',
    themeBg: 'rgb(129, 216, 208)',
  },
  {
    id: 'theme-color-10',
    basedOn: 'light',
    backgroundHeader: 'rgb(131, 126, 120)',
    colorText: 'dark',
    themeBg: 'rgb(226, 220, 210)',
  },
  {
    id: 'theme-color-11',
    basedOn: 'light',
    backgroundHeader: 'rgb(140, 132, 126)',
    colorText: 'dark',
    themeBg: 'rgb(255, 235, 205)',
  },
  {
    id: 'theme-color-12',
    basedOn: 'light',
    backgroundHeader: 'rgb(116, 122, 99)',
    colorText: 'dark',
    themeBg: 'rgb(231, 238, 210)',
  },
  {
    id: 'theme-color-13',
    basedOn: 'light',
    backgroundHeader: 'rgb(85, 111, 116)',
    colorText: 'dark',
    themeBg: 'rgb(208, 240, 247)',
  },
  {
    id: 'theme-color-14',
    basedOn: 'light',
    backgroundHeader: 'rgb(90, 94, 118)',
    colorText: 'dark',
    themeBg: 'rgb(201, 208, 251)',
  },
  {
    id: 'theme-color-15',
    basedOn: 'light',
    backgroundHeader: 'rgb(83, 95, 107)',
    colorText: 'dark',
    themeBg: 'rgb(221, 243, 255)',
  },
  {
    id: 'theme-color-16',
    basedOn: 'light',
    backgroundHeader: 'rgb(128, 128, 128)',
    colorText: 'dark',
    themeBg: 'rgb(240, 240, 240)',
  },
]

export let anotherThemes = [
  {
    id: 'default-dark',
    basedOn: 'dark',
    backgroundHeader: 'var(--color-accent-bg)',
    colorText: 'light',
    themeBg: 'var(--color-background-dark)',
    themeBgURL: 'another-theme--1',
  },
  {
    id: 'default-light',
    basedOn: 'light',
    backgroundHeader: 'var(--color-background-light)',
    colorText: 'dark',
    themeBg: 'var(--color-background-light)',
    themeBgURL: 'another-theme--2',
  },
  {
    id: 'theme-3',
    basedOn: 'light',
    backgroundHeader: '#6B1344',
    colorText: 'light',
    themeBgURL: 'another-theme-mini--3',
    themeBgImg: 'another-theme--3',
  },
]
